myapp/models.py
from myapp import db
from datetime import datetime


class Books(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(60), unique = True, nullable = False)
    author = db.Column(db.String(40), unique = True, nullable = False)
    description = db.Column(db.String(250), unique = True, nullable = False)
    cover = db.Column(db.String(40), unique = True, default = 'default.jpeg')
    pages_total = db.Column(db.Integer, unique = False, nullable = False)
    pages_read = db.Column(db.Integer, unique = False, default = 0)
    date_added = db.Column(db.Integer, unique = False, default = datetime.today)
    annotations = db.relationship("Notes", cascade="all, delete, delete-orphan",
                                    backref = "book", lazy = True)


class Notes(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    chapter_name = db.Column(db.String(60), nullable = False)
    page_from = db.Column(db.Integer, unique = False)
    page_to = db.Column(db.Integer, unique = False)
    ideas = db.Column(db.Text(), unique = False)
    book_id = db.Column(db.Integer, db.ForeignKey("books.id"), nullable = False)

myapp/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError, InputRequired


class BookForm(FlaskForm):
    # we can remove placeholders from here and put them in the html
    # same way as we did with UpdateBook, this way we don't mix
    # structural code with style.
    title = StringField("Title", validators=[Length(min=1, max=60),
                                             DataRequired()], render_kw={"placeholder": "Book title"})
    author = StringField("Author", validators=[Length(min=1, max=40),
                                               DataRequired()], render_kw={"placeholder": "Author's name"})
    description = TextAreaField("Description", validators=[Length(min=1, max=250)],
                                render_kw={"placeholder": "Book's description"})
    #passed Id for the Label tag in AddBook to identify the cover field in the class
    cover = FileField("Book cover", validators=[FileAllowed(['jpg', "jpeg"])], id="UploadLabel")
    pages_total = IntegerField("Pages", validators=[InputRequired()], render_kw={"placeholder": "Number of pages"})
    pages_read = IntegerField("Pages read", validators=[InputRequired()], render_kw={"placeholder": "Pages read"})
    submit = SubmitField("Add book")


class UpdateBook(FlaskForm):
    title = StringField("Title", validators=[Length(min=1, max=60), DataRequired()])
    author = StringField("Author", validators=[Length(min=1, max=40), DataRequired()])
    description = TextAreaField("Description", validators=[Length(min=1, max=250)])
    #passed Id for the Label tag in SubmitBook to identify the cover field in the class
    cover = FileField("Update book's cover", validators=[FileAllowed(['jpg'])], id="UpdateCoverLabel")
    pages_total = IntegerField("Pages", validators=[InputRequired()])
    pages_read = IntegerField("Pages read", validators=[InputRequired()])
    update = SubmitField("Update book")


class AddNote(FlaskForm):
    chapter = StringField("Chapter", validators=[Length(min=1, max=60), DataRequired()])
    from_page = StringField()
    to_page = StringField()
    ideas = TextAreaField("Notes", validators=[Length(min=1, max=2000), DataRequired()])
    add_note = SubmitField("Add note")

myapp/__init__.py
from flask import Flask
from myapp.config import Config
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

def create_app(config_class = Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    from myapp.routes import main
    app.register_blueprint(main)

    return app

myapp/routes.py
from flask import render_template,request, redirect, url_for, flash, Blueprint, current_app, jsonify
from myapp import db
from myapp.models import Books, Notes
from myapp.forms import BookForm, UpdateBook, AddNote
from myapp.utils import save_cover, delete_cover

main = Blueprint('main',__name__)


@main.route("/", methods = ['GET', 'POST'])
@main.route("/home", methods = ['GET', 'POST'])
def home():
    book_form = BookForm()
    book_cover = None
    if book_form.validate_on_submit():
        if book_form.cover.data:
            book_cover = save_cover(book_form.cover.data)

        book = Books(title = book_form.title.data, author = book_form.author.data,
                        description = book_form.description.data,
                        cover = book_cover,
                        pages_total = book_form.pages_total.data,
                        pages_read = book_form.pages_total.data)

        db.session.add(book)
        db.session.commit()
        flash('Added successfully!', 'success')
        return redirect(url_for('main.home'))

    return render_template("home.html", title = "Welcome!", form = book_form)


#route to query all my books
@main.route("/my_books", methods = ['GET', 'POST'])
def book_view():
    all_books = Books.query.all()
    return render_template("library.html", title = "My Library", library_content = all_books)



#route to delete the book entiries.
#this is a route that will receive AJAX request (req dict object)
#takes that book_ID from that request to query our DB.
@main.route("/my_books/delete/book", methods = ['POST'])
def delete_book():
    book_deletion = Books.query.filter_by(id = request.form['book_ID']).first() #this request comes from JS

    if book_deletion.cover != "default.jpeg":
        delete_cover(book_deletion.cover)

    db.session.delete(book_deletion)
    db.session.commit()
    flash('You have deleted the book!', 'success')
    return jsonify({"result" : "success"})



#gets called by the search button in the nav bar
#executes sql query LIKE %#%
@main.route("/search", methods = ["POST"])
def search_book():
    book_search = Books.query.filter(Books.title.like("%" + request.form["book_title"] + "%")).first()

    if book_search != None:
        return redirect(url_for("main.edit_book", book_id = book_search.id))
    else:
        flash('Title does not exist!', 'danger')
        return redirect(url_for("main.home"))



@main.route("/my_books/edit/<book_id>", methods = ['POST', 'GET'])
def edit_book(book_id):
    queried_book = Books.query.get_or_404(book_id)
    queried_notes = Notes.query.filter(Notes.book_id == book_id).order_by("page_from").all()
    #pass the queried book to the update book form, fillin in the data
    update_form = UpdateBook(obj = queried_book)
    add_notes = AddNote()


    if update_form.update.data and update_form.validate_on_submit():

        if update_form.cover.data != queried_book.cover:
            if queried_book.cover != "default.jpeg":
                delete_cover(queried_book.cover)
            cover_file = save_cover(update_form.cover.data)
            queried_book.cover = cover_file

        queried_book.title = update_form.title.data
        queried_book.author = update_form.author.data
        queried_book.description = update_form.description.data
        queried_book.pages_total = update_form.pages_total.data
        queried_book.pages_read = update_form.pages_read.data
        db.session.commit()
        return redirect(url_for("main.edit_book", book_id = book_id))


    elif add_notes.add_note.data and add_notes.validate_on_submit():
        note = Notes(chapter_name = add_notes.chapter.data , page_from = add_notes.from_page.data,
                        page_to = add_notes.to_page.data, ideas = add_notes.ideas.data, book_id = book_id)
        db.session.add(note)
        db.session.commit()
        return redirect(url_for("main.edit_book", book_id = book_id))

    #executed with View button in the library
    #view button calls edit_book and passes the book_id parameter
    #probably a really weird way to implement that
    elif request.method == "GET":
        return render_template("book_details.html", book = queried_book, book_notes = queried_notes,
                            update_form = update_form, notes_form = add_notes)

    return render_template("book_details.html", book = queried_book, book_notes = queried_notes,
                        update_form = update_form, notes_form = add_notes)



#this is a route that will receive AJAX request (req dict object)
#we take that note_ID from that AJX request to query our DB.
@main.route("/my_books/edit/note", methods = ['POST'])
def delete_note():
    #get_or_404 may be more flexible than filter_by
    note_deletion = Notes.query.get_or_404(request.form['note_ID'])
    db.session.delete(note_deletion)
    db.session.commit()
    return jsonify({"result" : "success"})

myapp/templates/book_details.html
{% extends 'layout.html'%}
{% block content %}


{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class="alert alert-info alert-dismissible" >
    {% for message in messages %}
      <li >{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}


<div class="card details-card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-details" role="tab" aria-controls="nav-details" aria-selected="true">Details</a>
      </li>
      <li class="nav-item">
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-add" role="tab" aria-controls="nav-add" aria-selected="false">Add note</a>
      </li>
    </ul>
  </div>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active pt-1" id="nav-details" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="card flex-row border-0" id =bookNumber{{book.id}} style="width: 80%;">
          <div class="card-header p-1">
              <img src="{{ url_for('static', filename = 'book_covers/' + book.cover) }}">
          </div>
          <div class="card-block px-1">
            <form action="" enctype="multipart/form-data" id ="SubmitBook" method="POST">
              {{ update_form.hidden_tag() }}
              <fieldset class = "form-group">
                <div class="form-group">
                  {% if update_form.title.errors %}
                    {{ update_form.title(class = "update_form-control update_form-control-sm is-invalid") }}
                    <div class="">
                      {% for error in update_form.title.errors %}
                        <span> {{ error }} </span>
                      {% endfor %}
                    </div>
                  {% else %}
                      {{ update_form.title(class_= "details-input-area") }}
                  {% endif %}
                </div>

                <div class="form-group">
                  {% if update_form.author.errors %}
                    {{ update_form.author(class = "update_form-control update_form-control-sm is-invalid") }}
                    <div class="">
                      {% for error in update_form.author.errors %}
                        <span> {{ error }} </span>
                      {% endfor %}
                    </div>
                  {% else %}
                      {{ update_form.author(class_= "details-input-area") }}
                  {% endif %}
                </div>

                <div class="form-group">
                  {% if update_form.pages_total.errors %}
                    {{ update_form.pages_total(class = "update_form-control update_form-control-sm is-invalid") }}
                    <div class="">
                      {% for error in update_form.pages_total.errors %}
                        <span> {{ error }} </span>
                      {% endfor %}
                    </div>
                  {% else %}
                      {{ update_form.pages_total(class_= "details-input-area") }}
                  {% endif %}
                </div>

                <div class="form-group">
                  {% if update_form.pages_read.errors %}
                    {{ update_form.pages_read(class = "update_form-control update_form-control-sm is-invalid") }}
                    <div class="">
                      {% for error in update_form.pages_read.errors %}
                        <span> {{ error }} </span>
                      {% endfor %}
                    </div>
                  {% else %}
                      {{ update_form.pages_read(class_= "details-input-area") }}
                  {% endif %}
                </div>

                <div class="form-group">
                  {% if update_form.cover.errors %}
                    {{ update_form.cover(class = "update_form-control update_form-control-sm is-invalid") }}
                    <div class="">
                      {% for error in update_form.cover.errors %}
                        <span> {{ error }} </span>
                      {% endfor %}
                    </div>
                  {% else %}
                    <label for="UpdateCoverLabel" class = "cover_update_label">
                      {{ update_form.cover(class_= "cover_update")}}
                    </label>
                  {% endif %}
                </div>

                <div class="form-group">
                  {% if update_form.description.errors %}
                    {{ update_form.description(class = "update_form-control update_form-control-sm is-invalid") }}
                    <div class="">
                      {% for error in update_form.description.errors %}
                        <span> {{ error }} </span>
                      {% endfor %}
                    </div>
                  {% else %}
                      {{ update_form.description(class_ = "text-area") }}
                  {% endif %}
                </div>

                <div class="log-button-container">
                  {{ update_form.update (class_="btn btn-danger") }}
                </div>
              </fieldset>
            </form>
          </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-add" role="tabpanel" aria-labelledby="nav-add-tab">
      <div class="add-note-card card my-1" style="width: 40%;">
        <form class="addnote" action="" method="POST">
          {{ update_form.hidden_tag() }}
          <ul class="list-group list-group-flush">
            <li class="list-group-item p-0">{{ notes_form.chapter(placeholder = "Chapter", class_= "ideas-input-area") }}</li>
            <li class="list-group-item p-0">{{ notes_form.from_page(placeholder =  "From page", class_= "ideas-input-area") }}</li>
            <li class="list-group-item p-0">{{ notes_form.to_page(placeholder = "To page", class_= "ideas-input-area") }}</li>
            <li class="list-group-item p-0">{{ notes_form.ideas(placeholder = "Notes", class_ = "ideas-text-area" ) }}</li>
            {{ notes_form.add_note(class_="btn btn-danger")}}
          </ul>
        </form>
      </div>
    </div>
  </div>
</div>



<div class="card-columns my-2 mx-2">
  {% for note in book_notes %}
    <div class="card note-card border-dark mr-1" id = "noteNumber{{ note.id }}">
      <div class="card-header">{{ note.chapter_name }}</div>
      <div class="card-body">
        <p class="card-text">{{ note.ideas }}</p>
        <p class="card-text"><small class="text-muted">Page {{ note.page_from }}<span> to {{ note.page_to}}</span></small></p>
      </div>
      <button class = "note-delete-btn btn-dark deleteNote" note_id = "{{ note.id }}">Delete</button>
    </div>
  {% endfor %}
</div>



{% endblock %}

myapp/templates/home.html
{% extends "layout.html" %}
{% block content %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class="alert alert-info alert-dismissible">
    {% for message in messages %}
      <li >{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

<div class="add-book-card card my-1 border-0">
  <form class="AddBook" action="" enctype="multipart/form-data" id ="SubmitBook" method="post">
    {{ form.hidden_tag() }}
    <fieldset>

      <div class="card-header p-1">
        <label for = "UploadLabel" class = "cover_upload_label">
          {{ form.cover(class_="cover_upload") }}
        </label>
      </div>

      <div class="form-group">
        {% if form.title.errors %}
          {{ form.title(class = "form-control form-control-sm is-invalid") }}
          <div class="">
            {% for error in form.title.errors %}
              <span> {{ error }} </span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.title(class = "newbook-input-area") }}
        {% endif %}
      </div>

      <div class="form-group">
        {% if form.author.errors %}
          {{ form.author(class = "form-control form-control-sm is-invalid") }}
          <div class="">
            {% for error in form.author.errors %}
              <span> {{ error }} </span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.author(class = "newbook-input-area") }}
        {% endif %}
      </div>

      <div class="form-group">
        {% if form.description.errors %}
          {{ form.description(class = "form-control form-control-sm is-invalid") }}
          <div class="">
            {% for error in form.description.errors %}
              <span> {{ error }} </span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.description(class = "new-book-description") }}
        {% endif %}
      </div>
      <div class="row">
        <div class="form-group col-md-6">
          {% if form.pages_total.errors %}
            {{ form.pages_total(class = "form-control form-control-sm is-invalid") }}
            <div class="">
              {% for error in form.pages_total.errors %}
                <span> {{ error }} </span>
              {% endfor %}
            </div>
          {% else %}
              {{ form.pages_total(class = "newbook-input-area") }}
          {% endif %}
        </div>

        <div class="form-group col-md-6">
          {% if form.pages_read.errors %}
            {{ form.pages_read(class = "form-control form-control-sm is-invalid") }}
            <div class="">
              {% for error in form.pages_read.errors %}
                <span> {{ error }} </span>
              {% endfor %}
            </div>
          {% else %}
              {{ form.pages_read(class = "newbook-input-area") }}
          {% endif %}
        </div>
      </div>

      {{ form.submit(class_="btn btn-danger") }}
    </fieldset>
  </form>
</div>

{% endblock %}

myapp/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename="app.js") }}"></script>
    <link rel="stylesheet" type = "text/css" href='{{ url_for('static', filename = 'bootstrap.min.css') }}'>
    <link rel="stylesheet" type = 'text/css' href = '{{ url_for('static', filename = 'custom.css') }}'>

    {% if title %}
      <title>{{title}}</title>
    {% else %}
      <title>Default</title>
    {% endif %}
    <title></title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href={{ url_for('main.home') }}><img src="{{ url_for('static', filename="navitem.png")}}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapsed" aria-controls="navbarCollapsed" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapsed">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-item nav-link" href="{{ url_for('main.book_view') }}">My Books</a>
            </li>
          </ul>
          <form class="form-inline" action="{{ url_for('main.search_book') }}" method = "POST">
            <input class="form-control h-25 mr-sm-2" name = "book_title" type="search" placeholder="Search books" aria-label="Search" required>
            <button class="btn btn-danger btn-sm mt-2 " type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>


    {% block content %} {% endblock %}

  </body>
</html>

myapp/templates/library.html
{% extends "layout.html"%}
{% block content %}

{% for book in library_content %}


  <div class="card library-card border-0 mt-2" id = bookNumber{{book.id}} >
       <div class="row align-items-start no-gutters">
           <div class="col-auto img-col mx-auto">
               <img src="{{ url_for('static', filename = 'book_covers/' + book.cover) }}">
           </div>
           <div class="w-1 breaker">
             <!-- breaks the card in one columns, source: Bootstrap Grid System : Column Breakers -->
           </div>
           <div class="col mx-auto">
               <div class="card-block px-1 mb-2">
                 <h4 class="card-header">{{ book.title }}</h4>
                 <p class="card-text">Author : {{ book.author }}</p>
                 <p class="card-text">Pages : {{ book.pages_total }}</p>
                 <p class="card-text">Pages read : {{ book.pages_read }}</p>
                 <p class="card-text">Date added : {{ book.date_added[:10] }}</p>
                 <p class="card-text description">{{ book.description }}</p>
               </div>
               <form class = view-form action="{{ url_for('main.edit_book', book_id = book.id) }}" method="GET">
                 <input class = "btn btn-info view-btn" type="submit" name="update" value="View">
               </form>
               <button class = "btn btn-danger deleteBook" book_id="{{ book.id }}">Delete</button>
           </div>


       </div>
 </div>
{% endfor %}

{% endblock %}